name: Create and publish Docker image

on: 
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vite-react-chainguard

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read
      packages: write
      attestations: write
      id-token: write
      security-events: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: ðŸ› ï¸ Set up QEMU (Multi-arch support)
        uses: docker/setup-qemu-action@v3
      
      - name: âš™ï¸ Set up Docker Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule, pattern=nightly
            type=ref, event=branch, enable=true
            type=ref, event=pr, enable=true
            type=semver, pattern={{version}}
            type=semver, pattern={{major}}.{{minor}}
            type=ref, event=branch, suffix=-{{sha}}
            type=ref, event=tag, enable=true
            type=sha, prefix=sha-

      - name: Build and push images to ghcr
        id: push
        uses: docker/build-push-action@v6
        with:
          context: 2025/vite-react-template
          file: 2025/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          sbom: true
          provenance: mode=max
          cache-from: type=gha
          cache-to: type=gha, mode=max
          platforms: linux/amd64, linux/arm64

  scan-and-report:
    runs-on: ubuntu-latest
    needs: [build-and-push-image]
    
    permissions:
      contents: write
      actions: read
      packages: write
      attestations: write
      id-token: write
      security-events: write
    
    steps:
      - name: Get information
        id: ref
        run: |
          PUSH_DIGEST="${{ needs.build-and-push-image.outputs.digest }}"
          LOCAL_TAG="${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:main"
          
          if [[ -n "$PUSH_DIGEST" ]]; then
              TAGS="${{ needs.build-and-push-image.outputs.tags }}"
              TAG_NAME=$(echo "$TAGS" | head -n 1 | tr -d '[:space:]')
              IMAGE_REFERENCE="$TAG_NAME@$PUSH_DIGEST"
              echo "INFO: Scanning PUSHED image using DIGEST."
          else
              IMAGE_REFERENCE="$LOCAL_TAG"
              echo "INFO: Scanning LOCAL image using TAG."
          fi
          
          echo "IMAGE_REFERENCE=$IMAGE_REFERENCE" >> $GITHUB_OUTPUT

      - name: Scan with Grype
        id: scan
        uses: anchore/scan-action@v6
        with:
          image: ${{ steps.ref.outputs.IMAGE_REFERENCE }}
          severity-cutoff: high
          output-file: ${{ runner.temp }}/grype.sarif

      - name: Upload results to github
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() }}
        with:
          sarif_file: ${{ runner.temp }}/grype.sarif
      