name: Create and publish Docker image

on: 
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vite-react-chainguard

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: üõ†Ô∏è Set up QEMU (Multi-arch support)
        uses: docker/setup-qemu-action@v3
      
      - name: ‚öôÔ∏è Set up Docker Buildx (BuildKit)
        uses: docker/setup-buildx-action@v3

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule, pattern=nightly
            type=ref, event=branch, enable=true
            type=ref, event=pr, enable=true
            type=semver, pattern={{version}}
            type=semver, pattern={{major}}.{{minor}}
            type=ref, event=branch, suffix=-{{sha}}
            type=ref, event=tag, enable=true
            type=sha, prefix=sha-

      - name: Build and push images to ghcr
        id: push
        uses: docker/build-push-action@v6
        with:
          context: 2025/vite-react-template
          file: 2025/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha, mode=max
          platforms: linux/amd64, linux/arm64
      
      - name: SBOM scanning
        uses: anchore/sbom-action@v0
        id: sbom-scan
        with:
          image: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
          format: spdx-json
          output-file: "${{ env.IMAGE_NAME }}-sbom.spdx.json"
      
      - name: Scan with Grype
        uses: anchore/scan-action@v6
        with:
          sbom: "${{ env.IMAGE_NAME }}-sbom.spdx.json"
          fail-build: true
          severity-cutoff: high
      
      - name: Get attestations
        uses: actions/attest-sbom@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          sbom-path: "${{ env.IMAGE_NAME }}-sbom.spdx.json"
          push-to-registry: true
